services:
  web:
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/acme:/var/www/acme:ro
      - ./web/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
  backend:
    environment:
      APP_URL: https://52.70.7.30
      SESSION_SECURE_COOKIE: "true"
